### ISSUE TITLE
pogoprotos-java

### ISSUE THREAD

**Issue by celandro** [Furtif/POGOProtos#5]
Ive looked at what you are doing and I'm so glad someone picked up for the dead repo.

I've been updating https://github.com/celandro/pogoprotos-java for use on https://www.pokebattler.com and https://github.com/BrunnerLivio/pokemongo-game-master for json generation which is used on multiple sites.

I believe that these repos should be linked in the readme (per the pull request on the other repo). The pogoprotos-java might make a good dependency for your java api if you think a minor refactor would be worth it.

**Comment by Furtif** [comment]
Hello, I have kept this protos and pogolib, the problem is that before I had the base as you can see in the "base" directory and I had it better but now I do not have it so that the gyms part is not up to date, if for some reason Maybe you have a proto raw send it to me that will update it. I'm in several discords meni nickname is the same as here is not to cheat.

Thank you for the support
